import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';

const righteous = localFont({
  src: "./fonts/Righteous-Regular.woff",
  variable: "--font-righteous-regular",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Contractr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
        <ColorSchemeScript />
      </head>
      <body
        className={`${righteous.variable} antialiased`}
      >
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
